//! Deterministic counteroffer planner for NXT negotiation autopilot.
//!
//! Given a concession envelope, generates ranked counteroffer alternatives
//! with stable ordering and deterministic tie-break behavior.
//!
//! Strategy templates define how alternatives are generated (e.g., step-down
//! from ceiling, split-the-difference, anchor-high). The planner applies the
//! selected strategy and ranks results by a configurable priority field.

use serde::{Deserialize, Serialize};

use crate::domain::negotiation::{
    ConcessionEnvelope, ConcessionRange, CounterofferAlternative, CounterofferPlan,
};

// ---------------------------------------------------------------------------
// Strategy templates
// ---------------------------------------------------------------------------

/// Strategy for generating counteroffer alternatives.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum CounterofferStrategy {
    /// Step down from ceiling in fixed increments.
    StepDown,
    /// Split the difference between current and floor.
    SplitDifference,
    /// Anchor high: start near ceiling and offer small concessions.
    AnchorHigh,
}

impl CounterofferStrategy {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::StepDown => "step_down",
            Self::SplitDifference => "split_difference",
            Self::AnchorHigh => "anchor_high",
        }
    }

    pub fn parse_label(s: &str) -> Option<Self> {
        match s {
            "step_down" => Some(Self::StepDown),
            "split_difference" => Some(Self::SplitDifference),
            "anchor_high" => Some(Self::AnchorHigh),
            _ => None,
        }
    }
}

/// Configuration for counteroffer generation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CounterofferConfig {
    pub strategy: CounterofferStrategy,
    /// Maximum number of alternatives to generate.
    pub max_alternatives: u32,
    /// Tie-break field for deterministic ranking.
    pub tie_break_field: String,
    /// Step size override (if None, uses dimension policy step).
    pub step_override: Option<f64>,
}

impl Default for CounterofferConfig {
    fn default() -> Self {
        Self {
            strategy: CounterofferStrategy::StepDown,
            max_alternatives: 3,
            tie_break_field: "discount_pct".to_string(),
            step_override: None,
        }
    }
}

// ---------------------------------------------------------------------------
// Planner
// ---------------------------------------------------------------------------

/// Deterministic counteroffer planner. Stateless.
#[derive(Debug, Clone, Default)]
pub struct CounterofferPlanner;

impl CounterofferPlanner {
    /// Generate a ranked counteroffer plan from the concession envelope.
    ///
    /// The primary dimension is the `tie_break_field` in config. Alternatives
    /// are generated by varying that dimension within the envelope range.
    pub fn plan(
        &self,
        envelope: &ConcessionEnvelope,
        config: &CounterofferConfig,
    ) -> CounterofferPlan {
        let primary_range = envelope.ranges.iter().find(|r| r.dimension == config.tie_break_field);

        let alternatives = match primary_range {
            Some(range) => match config.strategy {
                CounterofferStrategy::StepDown => self.step_down(range, config),
                CounterofferStrategy::SplitDifference => self.split_difference(range, config),
                CounterofferStrategy::AnchorHigh => self.anchor_high(range, config),
            },
            None => Vec::new(),
        };

        CounterofferPlan {
            session_id: envelope.session_id.clone(),
            alternatives,
            tie_break_field: config.tie_break_field.clone(),
        }
    }

    /// Step down from ceiling in fixed increments.
    fn step_down(
        &self,
        range: &ConcessionRange,
        config: &CounterofferConfig,
    ) -> Vec<CounterofferAlternative> {
        let step = config.step_override.unwrap_or(if range.ceiling > range.floor {
            (range.ceiling - range.floor) / (config.max_alternatives as f64 + 1.0)
        } else {
            1.0
        });

        let mut alts = Vec::new();
        let mut value = range.ceiling;
        let mut rank = 1u32;

        while rank <= config.max_alternatives && value >= range.floor {
            alts.push(CounterofferAlternative {
                offer_id: format!("offer-{}-{rank}", config.strategy.as_str()),
                rank,
                discount_pct: value,
                term_months: None,
                rationale: format!(
                    "Step-down offer: {:.1}% (step {rank} of {})",
                    value, config.max_alternatives
                ),
            });
            value -= step;
            rank += 1;
        }

        alts
    }

    /// Split the difference between current and floor.
    fn split_difference(
        &self,
        range: &ConcessionRange,
        config: &CounterofferConfig,
    ) -> Vec<CounterofferAlternative> {
        let mut alts = Vec::new();
        let mut value = range.current;
        let mut rank = 1u32;

        while rank <= config.max_alternatives && value >= range.floor {
            alts.push(CounterofferAlternative {
                offer_id: format!("offer-split-{rank}"),
                rank,
                discount_pct: value,
                term_months: None,
                rationale: format!(
                    "Split-difference offer: {:.1}% (midpoint iteration {rank})",
                    value
                ),
            });
            // Each step halves the distance to floor
            value = (value + range.floor) / 2.0;
            rank += 1;
        }

        alts
    }

    /// Anchor high: start near ceiling and offer small concessions.
    fn anchor_high(
        &self,
        range: &ConcessionRange,
        config: &CounterofferConfig,
    ) -> Vec<CounterofferAlternative> {
        let total_range = range.ceiling - range.floor;
        // Start at 90% of ceiling, give small steps
        let start = range.ceiling - total_range * 0.1;
        let small_step = config.step_override.unwrap_or(total_range * 0.05);

        let mut alts = Vec::new();
        let mut value = start;
        let mut rank = 1u32;

        while rank <= config.max_alternatives && value >= range.floor {
            alts.push(CounterofferAlternative {
                offer_id: format!("offer-anchor-{rank}"),
                rank,
                discount_pct: value,
                term_months: None,
                rationale: format!("Anchor-high offer: {:.1}% (small concession {rank})", value),
            });
            value -= small_step;
            rank += 1;
        }

        alts
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use crate::domain::negotiation::NegotiationSessionId;

    use super::*;

    fn test_envelope(ranges: Vec<ConcessionRange>) -> ConcessionEnvelope {
        ConcessionEnvelope {
            session_id: NegotiationSessionId("test-session".to_string()),
            ranges,
            blocking_reasons: Vec::new(),
        }
    }

    fn discount_range(current: f64) -> ConcessionRange {
        ConcessionRange {
            dimension: "discount_pct".to_string(),
            floor: 0.0,
            ceiling: 40.0,
            current,
        }
    }

    #[test]
    fn step_down_generates_ranked_alternatives() {
        let planner = CounterofferPlanner;
        let envelope = test_envelope(vec![discount_range(15.0)]);
        let config = CounterofferConfig {
            strategy: CounterofferStrategy::StepDown,
            max_alternatives: 3,
            ..Default::default()
        };

        let plan = planner.plan(&envelope, &config);

        assert_eq!(plan.alternatives.len(), 3);
        // Descending from ceiling
        assert!(plan.alternatives[0].discount_pct > plan.alternatives[1].discount_pct);
        assert!(plan.alternatives[1].discount_pct > plan.alternatives[2].discount_pct);
        // Ranks are 1, 2, 3
        assert_eq!(plan.alternatives[0].rank, 1);
        assert_eq!(plan.alternatives[1].rank, 2);
        assert_eq!(plan.alternatives[2].rank, 3);
    }

    #[test]
    fn split_difference_converges_toward_floor() {
        let planner = CounterofferPlanner;
        let envelope = test_envelope(vec![discount_range(30.0)]);
        let config = CounterofferConfig {
            strategy: CounterofferStrategy::SplitDifference,
            max_alternatives: 3,
            ..Default::default()
        };

        let plan = planner.plan(&envelope, &config);

        assert_eq!(plan.alternatives.len(), 3);
        // First offer is at current value
        assert_eq!(plan.alternatives[0].discount_pct, 30.0);
        // Second is midpoint between 30 and 0 = 15
        assert!((plan.alternatives[1].discount_pct - 15.0).abs() < 0.01);
        // Third is midpoint between 15 and 0 = 7.5
        assert!((plan.alternatives[2].discount_pct - 7.5).abs() < 0.01);
    }

    #[test]
    fn anchor_high_starts_near_ceiling() {
        let planner = CounterofferPlanner;
        let envelope = test_envelope(vec![discount_range(10.0)]);
        let config = CounterofferConfig {
            strategy: CounterofferStrategy::AnchorHigh,
            max_alternatives: 3,
            ..Default::default()
        };

        let plan = planner.plan(&envelope, &config);

        assert_eq!(plan.alternatives.len(), 3);
        // First offer should be close to ceiling (90% of 40 = 36)
        assert!(plan.alternatives[0].discount_pct > 30.0);
        // Descending
        assert!(plan.alternatives[0].discount_pct > plan.alternatives[1].discount_pct);
    }

    #[test]
    fn missing_tie_break_dimension_produces_empty_plan() {
        let planner = CounterofferPlanner;
        let envelope = test_envelope(vec![ConcessionRange {
            dimension: "margin_pct".to_string(),
            floor: 15.0,
            ceiling: 80.0,
            current: 40.0,
        }]);
        let config = CounterofferConfig {
            tie_break_field: "discount_pct".to_string(), // not in envelope
            ..Default::default()
        };

        let plan = planner.plan(&envelope, &config);

        assert!(plan.alternatives.is_empty());
    }

    #[test]
    fn deterministic_identical_inputs_identical_outputs() {
        let planner = CounterofferPlanner;
        let envelope = test_envelope(vec![discount_range(20.0)]);
        let config = CounterofferConfig::default();

        let plan1 = planner.plan(&envelope, &config);
        let plan2 = planner.plan(&envelope, &config);

        assert_eq!(plan1.alternatives.len(), plan2.alternatives.len());
        for (a, b) in plan1.alternatives.iter().zip(plan2.alternatives.iter()) {
            assert_eq!(a.offer_id, b.offer_id);
            assert_eq!(a.rank, b.rank);
            assert_eq!(a.discount_pct, b.discount_pct);
            assert_eq!(a.rationale, b.rationale);
        }
    }

    #[test]
    fn strategy_roundtrip() {
        let strategies = [
            CounterofferStrategy::StepDown,
            CounterofferStrategy::SplitDifference,
            CounterofferStrategy::AnchorHigh,
        ];
        for s in &strategies {
            let parsed = CounterofferStrategy::parse_label(s.as_str()).unwrap();
            assert_eq!(&parsed, s);
        }
        assert!(CounterofferStrategy::parse_label("bogus").is_none());
    }

    #[test]
    fn plan_respects_max_alternatives() {
        let planner = CounterofferPlanner;
        let envelope = test_envelope(vec![discount_range(10.0)]);
        let config = CounterofferConfig { max_alternatives: 5, ..Default::default() };

        let plan = planner.plan(&envelope, &config);

        assert!(plan.alternatives.len() <= 5);
    }
}
